import React from 'react'
import Head from 'next/head'

import { useRouter } from 'next/router'
import styled from 'styled-components'
import Sidebar from '../../components/Sidebar'
import ChatScreen from '../../components/ChatScreen'
export default function chatPage() {
    return (

        <>
            <Head>
                <title>myConnect</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ChatScreen />
        </>
    )
}
